name: Deploy

on:
  push:
    branches:
      - main  # Set the branch to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Replace with your build command if necessary

      - name: Start project
        run: npm start  # Replace with your start command

